// Songs that are popular somewhere else.
//
// Not a quality judgement and not the same thing as obscure. Every song listed
// here scores well - the median canonicity of the Brazilian funk alone is 86,
// and 78 of those tracks were tagged `standard`, meaning the sampler believed
// they were songs everyone knows. Casual dealt them about 1.7 times a night.
//
// The cause is that canonicity measures global curation and this table is in
// Stellenbosch. Deezer's Brazilian playlists are enormous, so a Sao Paulo funk
// set from 2023 collects more playlist appearances than most of the eighties,
// and every mechanism downstream reads that as fame. Nothing was broken: the
// measure answered the question it was asked, which turned out to be the wrong
// question.
//
// Excluded by ARTIST rather than by song, because these artists release
// constantly and the generator will keep finding them. A song list would need
// re-editing after every import; an artist list holds.
//
// This is deliberately a hand-checked list and not a rule. The same query that
// finds Mc IG also finds DJ Jazzy Jeff & The Fresh Prince, DJ Quik, MC Hammer,
// DJ Snake and DJ Khaled, and the pattern cannot tell them apart. A person can.
export const EXCLUDED_ARTISTS = new Set([
  "dj andreoli",
  "DJ Boy",
  "DJ GBR",
  "DJ GM",
  "DJ Gu",
  "DJ Guuga",
  "DJ Japa NK",
  "DJ Matt D",
  "DJ Oreia",
  "Dj Topo",
  "DJ Victor",
  "DJ WN",
  "dj yuri pedrada",
  "DJ Zullu",
  "Ludmilla",
  "Mc Bruninho da Praia",
  "MC Cebezinho",
  "Mc Cr\u00e9u",
  "Mc Davi",
  "Mc Don Juan",
  "MC Du Black",
  "MC Fioti",
  "MC G15",
  "Mc GP",
  "MC Gustta",
  "Mc Gw",
  "Mc Hariel",
  "Mc IG",
  "Mc Iguinho Ct",
  "MC Ingryd",
  "Mc J9",
  "Mc Joao",
  "Mc Joaozinho VT",
  "MC JottaP\u00ea",
  "MC Jvila",
  "MC Kadu",
  "MC Kekel",
  "Mc Kelvinho",
  "MC Kevin o Chris",
  "Mc Kevinho",
  "MC L da Vinte",
  "Mc Lan",
  "Mc Lele JP",
  "Mc Lipi",
  "MC Livinho",
  "MC Loma e As G\u00eameas Lacra\u00e7\u00e3o",
  "MC LUUKY",
  "MC Marcinho",
  "MC Marks",
  "Mc Menor da Vg",
  "MC MM",
  "Mc Neg\u00e3o Original",
  "Mc Neguinho do ITR",
  "Mc Paiva ZS",
  "MC Paulin da Capital",
  "Mc Pikachu",
  "Mc PP da VS",
  "MC Rahell",
  "Mc Rodolfinho",
  "MC Ryan SP",
  "MC WM",
  // Latin trap and reggaeton. Enormous globally, and Titi Me Pregunto was
  // removed by name before it was obvious that eight more of his tracks sat in
  // the pool on the same footing - NUEVAYoL at canonicity 87, DAKITI, Me Porto
  // Bonito. Removing them one at a time was going to be a standing chore.
  "Bad Bunny",
].map((a) => a.toLowerCase()));

// One-offs: the artist is not otherwise excluded, but this track is the same
// case. Mostly Brazilian, plus two French rap records that reached the pool the
// same way - Deezer is a French company and its index leans accordingly.
export const EXCLUDED_SONGS = new Set([
  "the box|the box medley funk 2",
  "the box|the box medley funk 6",
  "oruam|m\u00f3 temp\u00e3o que tu n\u00e3o fala comigo",
  "perlla|tremendo vacil\u00e3o",
  "bonde do tigr\u00e3o|o baile todo",
  "chimarruts|do lado de c\u00e1",
  "onze:20|n\u00e3o vai voltar",
  "onze:20|pra voc\u00ea",
  "gabriel o pensador|solit\u00e1rio surfista / surfista solit\u00e1rio",
  "latino|festa no ap\u00ea (dragostea din tei)",
  "luka|t\u00f4 nem a\u00ed",
  "furac\u00e3o 2000|dan\u00e7a da motinha",
  "chiclete com banana|100% voc\u00ea",
  "felipe dylon|musa do ver\u00e3o",
  "tribalistas|j\u00e1 sei namorar",
  "pk|quando a vontade bater (participa\u00e7\u00e3o especial de mc cabelinho)",
  "jean-jacques goldman|au bout de mes r\u00eaves",
  "iam|l'empire du c\u00f4t\u00e9 obscur",

  // Named at the table, after a first pass left them in as arguable. Each is
  // globally enormous and none of it lands here: a Spanish World Cup single from
  // 1998, two Latin tracks, and a Dutch producer's Brazilian sample.
  //
  // Song-level on purpose. Ricky Martin, Bad Bunny and The Weeknd all hold songs
  // this table does know - Livin' la Vida Loca, Blinding Lights, Starboy - so the
  // artist is not the thing that is wrong.
  "ricky martin|la copa de la vida (la canci\u00f3n oficial de la copa mundial, francia '98) (spanish version)",
  "bad bunny|tit\u00ed me pregunt\u00f3",
  "the weeknd|s\u00e3o paulo",
  "bakermat|baian\u00e1",

  // Latin trap and reggaeton beyond Bad Bunny - Pepas, Danza Kuduro, Gasolina,
  // and the KAROL G and Rauw Alejandro tracks that sit on the same footing.
  //
  // Then US country, cut to the most familiar 5% by request. The pool held 909
  // songs with country as their primary genre, 10.9% of a Casual night, and most
  // of it is US radio material - Kenny Chesney at 25 songs, George Strait at 19,
  // Alan Jackson at 16 - that a table in Stellenbosch has no way to place.
  //
  // Three things were kept back from that cut, and they are judgement rather
  // than measurement:
  //
  //   the top 5% by canonicity, ties included, which is a cutoff of 88
  //
  //   anything the household tagged itself, per the rule that a person outranks
  //   a rule
  //
  //   Jim Reeves, Don Williams, Kenny Rogers, Charley Pride, Johnny Cash, Dolly
  //   Parton, John Denver, Glen Campbell, Shania Twain, Willie Nelson and Patsy
  //   Cline in full. A global percentile does not know this country: Don Williams
  //   scores 78 and Jim Reeves 72, both below the cutoff, and both are staples
  //   here. This is the same blind spot rule 1 in docs/tagging.md exists for, and
  //   the reason canonicity is advisory rather than decisive.
  //
  // Bob Dylan, Lesley Gore, Nancy Sinatra, Harry Nilsson, Petula Clark, Bruno
  // Mars and a dozen others were also held back, for the duller reason that the
  // harvest tagged them country and they are not. Downtown and It's My Party
  // would have gone as country records.
  "daddy yankee|gasolina",
  "becky g|shower",
  "don omar|danza kuduro",
  "farruko|pepas",
  "becky g|mayores",
  "maluma|felices los 4",
  "becky g|mamiii",
  "rauw alejandro|tattoo",
  "karol g|provenza",
  "karol g|tqg",
  "travis tritt|it's a great day to be alive",
  "carrie underwood|before he cheats",
  "faith hill|this kiss",
  "faith hill|breathe",
  "ronnie milsap|smoky mountain rain",
  "martina mcbride|independence day",
  "leroy van dyke|walk on by",
  "lynn anderson|rose garden",
  "george strait|amarillo by morning",
  "the oak ridge boys|elvira",
  "eric church|springsteen",
  "keith urban|somebody like you",
  "tracy lawrence|time marches on",
  "deana carter|strawberry wine",
  "the judds|why not me",
  "alan jackson|livin' on love",
  "tim mcgraw|just to see you smile",
  "conway twitty|hello darlin'",
  "steve earle|copperhead road",
  "clint black|killin' time",
  "toby keith|as good as i once was",
  "brooks & dunn|red dirt road",
  "gretchen wilson|redneck woman",
  "dave dudley|six days on the road",
  "george jones|the race is on",
  "c.w. mccall|convoy",
  "johnny paycheck|take this job and shove it",
  "the charlie daniels band|the devil went down to georgia",
  "alan jackson|it's five o'clock somewhere",
  "dierks bentley|what was i thinkin'",
  "skeeter davis|the end of the world",
  "tammy wynette|d-i-v-o-r-c-e",
  "loretta lynn|don't come home a drinkin' (with lovin' on your mind)",
  "jimmy buffett|margaritaville",
  "george strait|love without end, amen",
  "brooks & dunn|ain't nothing 'bout you",
  "luke bryan|play it again",
  "blake shelton|austin",
  "faron young|hello walls",
  "tim mcgraw|it's your love",
  "rosanne cash|seven year ache",
  "kenny chesney|the good stuff",
  "trace adkins|honky tonk badonkadonk",
  "billy swan|i can help",
  "john michael montgomery|i swear",
  "marty robbins|devil woman",
  "faith hill|wild one",
  "tammy wynette|'til i can make it on my own",
  "george strait|does fort worth ever cross your mind",
  "ronnie milsap|lost in the fifties tonight",
  "brooks & dunn|brand new man",
  "toby keith|i love this bar",
  "brad paisley|mud on the tires",
  "kenny chesney|i go back",
  "craig morgan|that's what i love about sunday",
  "montgomery gentry|something to be proud of",
  "jake owen|barefoot blue jean night",
  "luke combs|when it rains it pours",
  "yardbirds|for your love",
  "luke bryan|rain is a good thing",
  "george hamilton iv|abilene",
  "little texas|god blessed texas",
  "leann rimes|blue",
  "david houston|almost persuaded",
  "loretta lynn|you ain't woman enough",
  "alabama|feels so right",
  "anne murray|could i have this dance",
  "alan jackson|remember when",
  "little big town|boondocks",
  "chris young|gettin' you home",
  "sara evans|suds in the bucket",
  "rascal flatts|life is a highway",
  "chris stapleton|tennessee whiskey",
  "josh turner|your man",
  "kenny chesney|there goes my life",
  "trace adkins|you're gonna miss this",
  "sam hunt|body like a back road",
  "luke combs|hurricane",
  "rodney atkins|take a back road",
  "ray price|for the good times",
  "earl thomas conley|fire and smoke",
  "merle haggard|pancho and lefty",
  "joe nichols|brokenheartsville",
  "lee ann womack|i hope you dance",
  "kenny chesney|american kids",
  "tracy lawrence|paint me a birmingham",
  "bobbie gentry|ode to billie joe",
  "ricochet|daddy's money",
  "merle haggard|mama tried",
  "jeannie c. riley|harper valley p.t.a.",
  "porter wagoner|green, green grass of home",
  "henson cargill|skip a rope",
  "bobby bare|500 miles away from home",
  "george strait|ocean front property",
  "tanya tucker|would you lay with me (in a field of stone)",
  "conway twitty|linda on my mind",
  "merle haggard|okie from muskogee",
  "crystal gayle|don't it make my brown eyes blue",
  "brooks & dunn|hard workin' man",
  "brad paisley|she's everything",
  "martina mcbride|this one's for the girls",
  "toby keith|i wanna talk about me",
  "george strait|troubadour",
  "blake shelton|honey bee",
  "jason aldean|big green tractor",
  "jon pardi|head over boots",
  "florida georgia line|this is how we roll",
  "the edwin hawkins singers|oh happy day",
  "albert hammond|it never rains in southern california",
  "miley cyrus|the climb",
  "leonard cohen|so long, marianne",
  "neil sedaka|happy birthday sweet sixteen",
  "alison krauss & union station|when you say nothing at all",
  "the judds|love can build a bridge",
  "bobby bare|detroit city",
  "darius rucker|alright",
  "floyd cramer|last date",
  "hank snow|i've been everywhere",
  "loretta lynn|one's on the way",
  "porter wagoner|the carroll county accident",
  "lefty frizzell|saginaw, michigan",
  "steve earle|guitar town",
  "kenny chesney|no shoes, no shirt, no problems",
  "the mavericks|dance the night away",
  "chely wright|single white female",
  "miranda lambert|the house that built me",
  "rascal flatts|bless the broken road",
  "zac brown band|toes",
  "randy houser|runnin' outta moonlight",
  "rascal flatts|what hurts the most",
  "luke combs|she got the best of me",
  "luke combs|one number away",
  "luke combs|beer never broke my heart",
  "zach bryan|pink skies",
  "ella langley|you look like you love me",
  "andy williams|can't take my eyes off you",
  "the yardbirds|heart full of soul",
  "dean martin|everybody loves somebody",
  "mickey & sylvia|love is strange",
  "blood, sweat & tears|you've made me so very happy",
  "mary chapin carpenter|shut up and kiss me",
  "george strait|give it away",
  "bobby bare|the streets of baltimore",
  "eddy arnold|then you can tell me goodbye",
  "george jones|walk through this world with me",
  "exile|kiss you all over",
  "tanya tucker|delta dawn",
  "juice newton|angel of the morning",
  "mark chesnutt|too cold at home",
  "mary chapin carpenter|passionate kisses",
  "blake shelton|some beach",
  "keith urban|days go by",
  "easton corbin|a little more country than that",
  "brad paisley|i'm gonna miss her",
  "faith hill|the way you love me",
  "billy currington|people are crazy",
  "toby keith|courtesy of the red, white and blue (the angry american)",
  "josh turner|would you go with me",
  "old dominion|snapback",
  "florida georgia line|dirt",
  "jason aldean|burnin' it down",
  "blake shelton|sure be cool if you did",
  "jake owen|american country love song",
  "florida georgia line|h.o.l.y.",
  "shaboozey|good news",
  "brad paisley|then",
  "bailey zimmerman|rock and a hard place",
  "jason aldean|the truth",
  "the band perry|if i die young",
  "luke bryan|crash my party",
  "tim mcgraw|highway don't care",
  "blake shelton|god's country",
  "scotty mccreery|five more minutes",
  "deana carter|did i shave my legs for this?",
  "bobby goldsboro|honey",
  "connie smith|i never once stopped loving you",
  "kitty wells|heartbreak u.s.a.",
  "starland vocal band|afternoon delight",
  "moe bandy|hank williams, you wrote my life",
  "tracy lawrence|i see it now",
  "keith whitley|don't close your eyes",
  "dan seals|everything that glitters (is not gold)",
  "alabama|the closer you get",
  "garth brooks|the dance",
  "faith hill|it matters to me",
  "lonestar|i'm already there",
  "jason aldean|amarillo sky",
  "chris young|voices",
  "keith urban|better life",
  "tim mcgraw|the cowboy in me",
  "rodney atkins|watching you",
  "faith hill|mississippi girl",
  "dierks bentley|i hold on",
  "luke bryan|drunk on you",
  "brantley gilbert|bottoms up",
  "kenny chesney|young",
  "eli young band|even if it breaks your heart",
  "florida georgia line|get your shine on",
  "sam hunt|leave the night on",
  "megan moroney|tennessee orange",
  "chris stapleton|parachute",
  "jake owen|beachin'",
  "old dominion|no such thing as a broken heart",
  "old dominion|written in the sand",
  "rascal flatts|yours if you want it",
  "brothers osborne|21 summer",
  "lanco|greatest love story",
  "joan baez|the night they drove old dixie down",
  "alan jackson|where were you (when the world stopped turning)",
  "gretchen wilson|here for the party",
  "walker hayes|fancy like",
  "miranda lambert|kerosene",
  "jason aldean|why",
  "gary allan|watching airplanes",
  "chris young|i'm comin' over",
  "carly pearce|every little thing",
  "brett young|mercy",
  "steve wariner|holes in the floor of heaven",
  "hank locklin|please help me, i'm falling",
  "the oak ridge boys|american made",
  "mary chapin carpenter|he thinks he'll keep her",
  "carl butler|don't let me cross over",
  "waylon jennings|good hearted woman",
  "porter wagoner|the cold hard facts of life",
  "mac davis|baby don't get hooked on me",
  "tom t. hall|country is",
  "funkadelic|maggot brain",
  "juice newton|queen of hearts",
  "keith urban|blue ain't your color",
  "chris ledoux|whatcha gonna do with a cowboy",
  "george strait|the cowboy rides away",
  "reba mcentire|whoever's in new england",
  "toby keith|whiskey girl",
  "kenny chesney|don't blink",
  "marty stuart|tempted",
  "jessica andrews|who i am",
  "tracy lawrence|find out who your friends are",
  "jerrod niemann|lover, lover",
  "montgomery gentry|my town",
  "carrie underwood|all-american girl",
  "dierks bentley|am i the only one",
  "cole swindell|chillin' it",
  "thomas rhett|die a happy man",
  "billy currington|don't it",
  "dustin lynch|cowboys and angels",
  "luke combs|beautiful crazy",
  "tucker wetmore|wind up missin’ you",
  "kane brown|heaven",
  "dan + shay|tequila",
  "dan + shay|all to myself",
  "sam hunt|take your time",
  "morgan wallen|up down",
  "luke bryan|sunrise, sunburn, sunset",
  "ella langley|weren't for the wind",
  "chris stapleton|you should probably leave",
  "dierks bentley|somewhere on a beach",
  "chris stapleton|broken halos",
  "thomas rhett|unforgettable",
  "megan moroney|6 months later",
  "riley green|don't mind if i do",
  "bailey zimmerman|backup plan",
  "hudson westbrook|house again",
  "post malone|guy for that",
  "pure prairie league|amie",
  "john michael montgomery|letters from home",
  "lee brice|love like crazy",
  "chris young|tomorrow",
  "blake shelton|i'll name the dogs",
  "dan + shay|10,000 hours",
  "dierks bentley|black",
  "jason aldean|rearview town",
  "walker hayes|you broke up with me",
  "maddie & tae|friends don't",
  "restless heart|when she cries",
  "david ball|thinkin' problem",
  "mindy mccready|ten thousand angels",
  "loretta lynn|blue kentucky girl",
  "\"little\" jimmy dickens|may the bird of paradise fly up your nose",
  "lefty frizzell|she's gone, gone, gone",
  "carpenters|top of the world",
  "billie jo spears|blanket on the ground",
  "ronnie milsap|it was almost like a song",
  "k.t. oslin|80's ladies",
  "ronnie milsap|(there's) no gettin' over me",
  "marty stuart|hillbilly rock",
  "brad paisley|ticks",
  "brad paisley|he didn't have to be",
  "brad paisley|wrapped around",
  "nanci griffith|lone star state of mind",
  "jimmie allen|freedom was a highway",
  "eminem|shake that",
  "mark wills|i do (cherish you)",
  "aaron tippin|you've got to stand for something",
  "tim mcgraw|everywhere",
  "sawyer brown|six days on the road",
  "lucinda williams|right in time",
  "clint black|put yourself in my shoes",
  "brett eldredge|don't ya",
  "justin moore|somebody else will",
  "dierks bentley|feel that fire",
  "toby keith|who's your daddy?",
  "jay sean|do you remember",
  "darryl worley|have you forgotten?",
  "bon jovi|who says you can't go home",
  "tim mcgraw|southern voice",
  "dierks bentley|come a little closer",
  "kenny chesney|don't happen twice",
  "kenny chesney|anything but mine",
  "kenny chesney|never wanted nothing more",
  "george strait|it just comes natural",
  "blake shelton|all about tonight",
  "luke bryan|i don't want this night to end",
  "lee brice|rumor",
  "kenny chesney|get along",
  "gloriana|(kissed you) good night",
  "luke bryan|move",
  "eric church|mr. misunderstood",
  "carrie underwood|church bells",
  "dan + shay|speechless",
  "lainey wilson|hang tight honey",
  "post malone|pour me a drink",
  "koe wetzel|high road",
  "maddie & tae|mood ring",
  "cole swindell|single saturday night",
  "kassi ashton|drive you out of my mind",
  "dustin lynch|small town boy",
  "russell dickerson|every little thing",
  "carrie underwood|undo it",
  "kane brown|lose it",
  "keith urban|the fighter",
  "cole swindell|you should be here",
  "brett young|in case you didn't know",
  "kip moore|more girls like you",
  "jordan davis|singles you up",
  "morgan wallen|whiskey glasses",
  "morgan wallen|i'm the problem",
  "russell dickerson|happen to me",
  "lainey wilson|somewhere over laredo",
  "jordan davis|bar none",
  "gavin adcock|last one to know",
  "morgan wallen|just in case",
  "riley green|worst way",
  "shaboozey|amen",
  "the cascades|rhythm of the rain",
  "kenny chesney|come over",
  "darius rucker|don't think i don't think about it",
  "sheryl crow|the first cut is the deepest",
  "blake shelton|mine would be you",
  "chris young|lonely eyes",
  "tyler, the creator|sugar on my tongue",
  "jordan davis|buy dirt",
  "hunter hayes|wanted",
  "riley green|i wish grandpas never died",
  "luke bryan|what makes you country",
  "darius rucker|if i told you",
  "blake shelton|every time i hear that song",
  "frank ifield|i remember you",
  "the tremeloes|silence is golden",
  "lou christie|lightnin' strikes",
  "hank snow|hello love",
  "sammi smith|help me make it through the night",
  "conway twitty|to see my angel cry",
  "skeeter davis|i forgot more than you'll ever know",
  "gene watson|love in the hot afternoon",
  "loretta lynn|feelins'",
  "linda ronstadt|you're no good",
  "waylon jennings|i'm a ramblin' man",
  "tracy lawrence|sticks and stones",
  "eddie rabbitt|the best year of my life",
  "k.t. oslin|this woman",
  "john anderson|countrified",
  "keith whitley|i wonder do you think of me",
  "steve wariner|life's highway",
  "t.g. sheppard|one for the money",
  "kathy mattea|come from the heart",
  "earl thomas conley|don't make it easy for me",
  "alan jackson|good time",
  "kenny chesney|out last night",
  "brad paisley|little moments",
  "brad paisley|alcohol",
  "thomas rhett|crash and burn",
  "tigirlily gold|shoot tequila",
  "clay walker|rumor has it",
  "reba mcentire|does he love you",
  "the wreckers|leave the pieces",
  "toby keith|i'm just talkin' about tonight",
  "paula deanda|when it was me",
  "kenny chesney|big star",
  "brad paisley|american saturday night",
  "jon pardi|night shift",
  "george strait|the seashores of old mexico",
  "george strait|wrapped",
  "lee brice|hard to love",
  "keith urban|cop car",
  "david nail|whatever she's got",
  "blake shelton|sangria",
  "avicii|the days",
  "artists of then, now & forever|forever country",
  "trace adkins|just fishin'",
  "luke combs|forever after all",
  "warren zeiders|pretty little poison",
  "morgan wallen|wasted on you",
  "niko moon|good time",
  "morgan wallen|you proof",
  "luke combs|the kind of love we make",
  "alan jackson|where have you gone",
  "florida georgia line|round here",
  "granger smith|backroad song",
  "thomas rhett|make me wanna",
  "thomas rhett|life changes",
  "russell dickerson|yours",
  "scotty mccreery|this is it",
  "brett eldredge|the long way",
  "brett young|catch",
  "dierks bentley|living",
  "riley green|there was this girl",
  "cody johnson|travelin' soldier",
  "darius rucker|come back song",
  "justin moore|you look like i need a drink",
  "thomas rhett|craving you",
  "kenny chesney|bar at the end of the world",
  "kacey musgraves|butterflies",
  "luke bryan|most people are good",
  "midland|burn out",
  "chris young|hangin' on",
  "ingrid andress|waste of lime",
  "michael ray|holy water",
  "tucker wetmore|3,2,1",
  "cameron whitcomb|medusa",
  "dasha|not at this party",
  "kevin powers|move on",
  "lauren alaina|all my exes",
  "jason aldean|how far does a goodbye go",
  "sam barber|music for the soul",
  "zach top|south of sanity",
  "aaron|u-turn (lili)",
  "tyler farr|redneck crazy",
  "morgan evans|kiss somebody",
  "tyler farr|a guy walks into a bar",
  "florida georgia line|simple",
  "zac brown band|colder weather",
  "kelsea ballerini|peter pan",
  "little big town|girl crush",
  "blake shelton|came here to forget",
  "chris janson|drunk girl",
  "eli young band|love ain't",
  "michael ray|one that got away",
  "randy travis|on the other hand",
  "trisha yearwood|xxx's and ooo's (an american girl)",
  "kathy mattea|eighteen wheels and a dozen roses",
  "the judds|grandpa (tell me 'bout the good old days)",
  "keith whitley|when you say nothing at all",
  "joe diffie|pickup man",
  "alabama|if you're gonna play in texas (you gotta have a fiddle in the band)",
  "pam tillis|maybe it was memphis",
  "mel mcdaniel|louisiana saturday night",
  "waylon jennings|luckenbach, texas (back to the basics of love) (feat. willie nelson)",
  "jo dee messina|bye-bye",
  "john anderson|straight tequila night",
  "kenny chesney|how forever feels",
  "tom t. hall|the year that clayton delaney died",
  "john anderson|swingin'",
  "k.t. oslin|do ya'",
  "sawyer brown|step that step",
  "the chicks|goodbye earl",
  "big & rich|save a horse (ride a cowboy)",
  "dwight yoakam|fast as you",
  "eddy arnold|make the world go away",
  "roger miller|dang me",
  "waylon jennings|theme from \"the dukes of hazzard\" (good ol' boys)",
  "julio iglesias|to all the girls i've loved before (with willie nelson)",
  "sawyer brown|some girls do",
  "toby keith|beer for my horses",
  "rhett akins|that ain't my truck",
  "martina mcbride|a broken wing",
  "alan jackson|drive (for daddy gene)",
  "trace adkins|every light in the house",
  "george jones|she thinks i still care",
  "george jones|golden ring",
  "george jones|the grand tour (single version)",
  "connie smith|once a day",
  "david allan coe|you never even called me by my name",
  "clint black|nobody's home",
  "alabama|down home",
  "billy currington|good directions",
  "leonard cohen|suzanne",
  "love affair|everlasting love",
  "blood, sweat & tears|spinning wheel",
  "kevin sharp|nobody knows",
  "gary stewart|she's actin' single (i'm drinkin' doubles)",
  "alabama|roll on (eighteen wheeler)",
  "rodney crowell|i couldn't leave you if i tried",
  "ricky van shelton|i'll leave this world loving you",
  "diamond rio|beautiful mess",
  "joe nichols|tequila makes her clothes fall off",
  "joe nichols|gimmie that girl",
  "henry mancini|moon river(vocal audrey hepburn)",
  "the kentucky headhunters|dumas walker",
  "eddy arnold|what's he doin' in my world",
  "charlie rich|behind closed doors (album version)",
  "freddy fender|before the next teardrop falls",
  "craig morgan|redneck yacht club",
  "kenny chesney|summertime",
  "claude king|wolverton mountain",
  "nina simone|i wish i knew how it would feel to be free",
  "charlie rich|the most beautiful girl",
  "daryle singletary|too much fun",
  "earl thomas conley|holding her and loving you",
  "the bellamy brothers|if i said you had a beautiful body would you hold it against me",
  "guy clark|desperados waiting for a train",
  "dan seals|bop",
  "earl thomas conley|right from the start",
  "emmylou harris|if i needed you",
  "neil young|get back to the country",
  "desert rose band|he's back and i'm blue",
  "hank williams, jr.|mind your own business",
  "highway 101|somewhere tonight",
  "mark chesnutt|bubba shot the jukebox",
  "randy travis|1982",
  "randy travis|diggin' up bones",
  "alan jackson|where i come from",
  "alan jackson|small town southern man",
  "alan jackson|country boy",
  "clay walker|what's it to you",
  "jason aldean|she's country",
  "trace adkins|ladies love country boys",
  "brooks & dunn|play something country",
  "the chicks|landslide",
  "eric church|smoke a little smoke",
  "the chicks|not ready to make nice",
  "brad paisley|whiskey lullaby (feat. alison krauss)",
  "the guess who|these eyes",
  "janis joplin|try (just a little bit harder)",
  "josé feliciano|light my fire",
  "tom t. hall|old dogs, children and watermelon wine (album version)",
  "dwight yoakam|streets of bakersfield",
  "alabama|tennessee river",
  "lorrie morgan|what part of no",
  "alan jackson|tall, tall trees",
  "george strait|i can still make cheyenne",
  "kenny chesney|when the sun goes down",
  "patty loveless|i try to think about elvis",
  "tim mcgraw|red ragtop",
  "rodney atkins|if you're going through hell (before the devil even knows)",
  "easton corbin|roll with it (album version)",
  "mark wills|19 somethin' (greatest hits version)",
  "westside connection|gangsta nation",
  "blake shelton|ol' red",
  "sam barber|indigo (feat. avery anna)",
  "vince gill|go rest high on that mountain",
  "randy travis|three wooden crosses",
  "keith urban|somewhere in my car",
  "little big town|better man",
  "bill anderson|still (single version)",
  "vince gill|don't let our love start slippin' away",
  "waylon jennings|are you sure hank done it this way",
  "wynn stewart|it's such a pretty world today (rerecorded)",
  "the oak ridge boys|leaving louisiana in the broad daylight",
  "john prine|angel from montgomery",
  "kris kristofferson|sunday mornin' comin' down",
  "donna fargo|the happiest girl in the whole u.s.a. (rerecorded)",
  "o. b. mcclinton|don't let the green grass fool you",
  "james talley|mehan, oklahoma",
  "loretta lynn|the pill",
  "sylvia|nobody",
  "emmylou harris|to know him is to love him",
  "foster and lloyd|crazy over you",
  "steve wariner|the weekend",
  "randy travis|he walked on water",
  "alanis morissette|head over feet (acoustic)",
  "lila mccann|i wanna fall in love",
  "aaron tippin|there ain't nothin' wrong with the radio",
  "miranda lambert|gunpowder & lead (album)",
  "blake shelton|boys 'round here (feat. pistol annies & friends)",
  "kenny chesney|all the pretty girls",
  "jon pardi|dirt on my boots",
  "florida georgia line|may we all",
  "townes van zandt|pancho and lefty",
  "the chicks|travelin' soldier",
  "billy currington|it don't hurt like it used to",
  "lady a|bartender",
  "aretha franklin|walk on by",
  "the mamas & the papas|dream a little dream of me (album version with introduction)",
  "vince gill|i still believe in you (album version)",
  "mark chesnutt|brother jukebox",
  "ernest tubb|waltz across texas",
  "faron young|wine me up (single version)",
  "terri gibbs|somebody's knockin' (album version)",
  "george strait|the fireman",
  "the judds|mama he's crazy",
  "ronnie milsap|he got you",
  "sweethearts of the rodeo|midnight girl / sunset town",
  "oak ridge boys|no matter how high",
  "zac brown band|as she's walking away (feat. alan jackson) (greatest hits version)",
  "terri clark|better things to do",
  "travis tritt|anymore",
  "the chicks|ready to run",
  "jo dee messina|lesson in leavin'",
  "dierks bentley|free and easy (down the road i go)",
  "luke bryan|someone else calling you baby",
  "craig morgan|international harvester",
  "billy currington|must be doin' somethin' right",
  "gary allan|nothing on but the radio",
  "roger miller|chug-a-lug (album version)",
  "trey songz|bottoms up (feat. nicki minaj)",
  "brad paisley|welcome to the future",
  "kenny chesney|you and tequila (feat. grace potter)",
  "steve holy|good morning beautiful (acoustic version)",
  "brothers osborne|it ain't my fault",
  "luke combs|ain't no love in oklahoma (from twisters: the album)",
  "midland|drinkin' problem",
  "kenny chesney|setting the world on fire (with p!nk)",
  "old dominion|song for another time",
  "ten years after|i'd love to change the world",
  "sugarland|stay (album version)",
  "eric church|round here buzz",
  "brantley gilbert|you don't know her like i do",
  "jason aldean|any ol' barstool",
  "kenny chesney|save it for a rainy day",
  "morgan wallen|what i want",
  "johnny winter|be careful with a fool",
  "leann rimes|one way ticket (because i can)",
  "pam tillis|don't tell me what to do",
  "mindy mccready|guys do it all the time",
  "the osborne brothers|rocky top",
  "george jones|tender years (single version)",
  "sonny james|you're the only world i know",
  "jerry lee lewis|what's made milwaukee famous (has made a loser out of me)",
  "linda ronstadt|when will i be loved",
  "the allman brothers band|midnight rider",
  "rick james|mary jane",
  "the statler brothers|silver medals and sweet memories",
  "the statler brothers|i'll go to my grave loving you (single version)",
  "the statler brothers|do you remember these?",
  "the statler brothers|bed of roses",
  "the statler brothers|your picture in the paper",
  "tammy wynette|kids say the darndest things",
  "kendalls|heaven's just a sin away (re-recording)",
  "merle haggard & the strangers|if we make it through december",
  "barbara mandrell|sleeping single in a double bed (single version)",
  "george strait|fool hearted memory",
  "dan seals|meet me in montana",
  "tracy lawrence|texas tornado",
  "alan jackson|midnight in montgomery",
  "restless heart|that rock won't roll",
  "restless heart|fast movin' train",
  "brooks & dunn|you're gonna miss me when i'm gone",
  "george strait|baby's gotten good at goodbye",
  "dwight yoakam|little ways",
  "the judds|rockin' with the rhythm of the rain",
  "the kentucky headhunters|walk softly on this heart of mine",
  "ricky van shelton|somebody lied",
  "keith whitley|i'm over you",
  "alabama|high cotton",
  "dwight yoakam|honky tonk man",
  "terri clark|girls lie too (greatest hits version)",
  "tim mcgraw|my next thirty years",
  "kenny chesney|you had me from hello",
  "the chicks|you were mine",
  "joe diffie|is it cold in here",
  "mark chesnutt|ol' country",
  "dierks bentley|woman, amen",
  "the chicks|long time gone",
  "josh turner|all over me",
  "justin moore|small town usa",
  "keith anderson|pickin' wildflowers",
  "jamie foxx|unpredictable (feat. ludacris) (main)",
  "billy currington|that's how country boys roll",
  "zac brown band|free (greatest hits version)",
  "luke bryan|all my friends say",
  "james otto|just got started lovin' you",
  "kenny chesney|somewhere with you",
  "eric church|talladega",
  "brad paisley|remind me (with carrie underwood)",
  "old dominion|hotel key",
  "maren morris|my church",
  "cole swindell|flatliner (feat. dierks bentley)",
  "blake shelton|a guy with a girl",
  "jon pardi|heartache on the dance floor",
  "luke combs|where the wild things are",
  "thomas rhett|after all the bars are closed",
  "dion|the wanderer",
  "gary puckett and the union gap|young girl",
  "lester flatt|the ballad of jed clampett (with the foggy mountain boys)",
  "blake shelton|she's got a way with words",
  "cole swindell|middle of a memory",
  "miranda lambert|mama's broken heart (album)",
  "kacey musgraves|follow your arrow",
  "kane brown|what ifs (feat. lauren alaina)",
  "dierks bentley|different for girls",
  "max mcnown|better me for you (brown eyes)",
  "the byrds|my back pages",
  "collin raye|love, me",
  "mary chapin carpenter|down at the twist and shout",
  "patty loveless|blame it on your heart",
  "kathy mattea|where've you been",
  "randy houser|boots on",
  "hank thompson|hangover heart",
  "connie smith|cincinnati, ohio",
  "ray charles|you don't know me",
  "carl & pearl butler|don't let me cross over",
  "bill anderson|mama sang a song",
  "del reeves|the girl on the billboard",
  "roy clark|yesterday when i was young",
  "hank thompson|oklahoma hills",
  "bill anderson|bright lights and country music (re-recorded in stereo)",
  "mark wills|don't laugh at me",
  "conway twitty|that's my job",
  "kris kristofferson|help me make it through the night",
  "kendalls|pittsburgh stealers (re-recording)",
  "sammy kershaw|third rate romance",
  "sammy kershaw|cadillac style",
  "bobby bare|how i got to memphis",
  "the flying burrito brothers|wild horses",
  "tanya tucker|blood red and goin' down",
  "merle haggard & the strangers|the fightin' side of me",
  "exile|woke up in love (exile)",
  "clint black|a better man",
  "toby keith|wish i didn't know now",
  "sawyer brown|thank god for you",
  "george strait|you look so good in love",
  "george strait|the chair",
  "george strait|baby blue",
  "tracy lawrence|as any fool can see",
  "sweethearts of the rodeo|since i found you",
  "dwight yoakam|little sister",
  "alabama|forty hour week (for a livin')",
  "shenandoah|ghost in this house",
  "barbara mandrell|crackers (single version)",
  "the forester sisters|(i'd choose) you again",
  "patty loveless|chains",
  "steve wariner|kansas city lights",
  "k.t. oslin|hold me",
  "ricky van shelton|i've cried my last tear for you",
  "eddie rabbitt|step by step",
  "dan seals|addicted",
  "michael martin murphey|a long line of love",
  "the forester sisters|i fell in love again last night",
  "the forester sisters|mama's never seen those eyes",
  "rosanne cash|tennessee flat top box",
  "restless heart|why does it have to be (wrong or right)",
  "shelly west|jose cuervo",
  "highway 101|the bed you made for me",
  "ricky van shelton|crime of passion",
  "ricky van shelton|wild man",
  "desert rose band|one step forward",
  "exile|give me one more chance",
  "alan jackson|i'll try",
  "mark chesnutt|it's a little too late (1996 greatest hits version)",
  "travis tritt|help me hold on",
  "marty stuart|this one's gonna hurt you (for a long, long time)",
  "gary allan|her man",
  "nivea|okay (feat. lil jon & youngbloodz) (album version)",
  "brooks & dunn|you can't take the honky tonk out of the girl",
  "craig morgan|almost home",
  "confederate railroad|trashy women",
  "john michael montgomery|i love the way you love me",
  "iris dement|our town",
  "john prine|all the best",
  "daryle singletary|the note",
  "steve earle|telephone road (with the fairfield four)",
  "gretchen peters|on a bus to st. cloud",
  "kelly willis|heaven's just a sin away",
  "little texas|kick a little",
  "jo dee messina|my give a damn's busted",
  "paula deanda|walk away (remember me) (feat. the dey)",
  "kacey musgraves|slow burn",
  "ll cool j|headsprung",
  "david banner|play (album version edited)",
  "mystikal|danger (been so long) (feat. nivea)",
  "gary allan|songs about rain",
  "martina mcbride|concrete angel",
  "brooks & dunn|only in america",
  "montgomery gentry|hell yeah",
  "keith urban|you'll think of me (single version)",
  "brothers osborne|stay a little longer",
  "miranda lambert|somethin' bad (with carrie underwood) (duet with carrie underwood album)",
  "eli young band|crazy girl (single version)",
  "russell dickerson|blue tacoma",
  "rascal flatts|i like the sound of that",
  "morgan wallen|i got better",
  "lanco|born to love you",
  "keith urban|wasted time",
  "chris stapleton|millionaire",
  "zach top|i never lie",
  "bigxthaplug|hell at night (feat. ella langley)",
  "bigxthaplug|all the way (feat. bailey zimmerman)",
  "bailey zimmerman|lost (feat. the kid laroi)",

  // Everything from 2024 on, cut to the most familiar 5% - a cutoff of 96, which
  // is high because a very recent song either charted enormously or nobody has
  // heard it yet. 252 of 278 go. This is a timeline game and a 2025 release is
  // the hardest possible card: there is no memory to place it against, and half
  // of them will not be remembered in three years anyway. Espresso, Beautiful
  // Things, Die With A Smile, APT. and Not Like Us stay.
  //
  // Then three instrumentals, one real medley, and three live or novelty cuts.
  // A game where you name the year from hearing the song is a poor fit for a
  // record with no vocal in it.
  "moblack|yamore",
  "ella langley|choosin' texas",
  "tame impala|dracula",
  "tyla|push 2 start",
  "jazzy|no bad vibes",
  "post malone|i had some help",
  "rampa|say what",
  "zerb|addicted",
  "david guetta|beautiful people",
  "calvin harris|blessings",
  "alex wann|my love (2024)",
  "unfazed|a gira",
  "shakira|dai dai",
  "marshmello|miles on it",
  "hugel|movin' to the sun",
  "raye|where is my husband!",
  "jaden bojsen|let's go",
  "swedish house mafia|lioness",
  "kygo|whatever",
  "hugel|jamaican (bam bam)",
  "gigi perez|sailor song",
  "doechii|anxiety",
  "francis mercier|sauti",
  "artemas|i like the way you kiss me",
  "dua lipa|training season",
  "disiz|melodrama",
  "lady gaga|abracadabra",
  "zerb|location",
  "olivia dean|man i need",
  "disco lines|no broke boys",
  "madonna|bring your love",
  "tyla|jump",
  "mr. belt & wezol|it's not right but it's okay",
  "levi|jump",
  "hugel|patadas de ahogado / latín mafia, humbe",
  "rivo|last night",
  "hugel|think of me",
  "sombr|back to friends",
  "ravyn lenae|love me not",
  "sabrina carpenter|manchild",
  "hanumankind|big dawgs",
  "kendrick lamar|squabble up",
  "gotye|somebody (2024)",
  "zara larsson|midnight sun",
  "jennie|like jennie",
  "central cee|band4band",
  "addison rae|fame is a gun",
  "temper city|self aware",
  "bruno mars|i just might",
  "floyymenor|gata only",
  "teddy swims|the door",
  "jaxomy|pedro",
  "drake|push ups",
  "alok|deep in your love",
  "tate mcrae|it's ok i'm ok",
  "alex warren|fever dream",
  "sombr|12 to 12",
  "prospa|free your mind",
  "bts|swim",
  "katseye|animal",
  "doja cat|jealous type",
  "madison beer|make you mine",
  "daft punk|veridis quo",
  "tate mcrae|sports car",
  "lisa|rockstar",
  "jennie|mantra",
  "sonny fodera|somedays",
  "bella kay|iloveitiloveitiloveit",
  "mauvais djo|pilé (gospel)",
  "kendrick lamar|luther",
  "travis scott|4x4",
  "gunna|one of wun",
  "central cee|gbp",
  "quavo|legends",
  "playboi carti|all red",
  "avaion|wacuka",
  "bon entendeur|fio maravilha",
  "sombr|potential",
  "olivia rodrigo|the cure",
  "myles smith|stay (if you wanna dance)",
  "ariana grande|we can't be friends (wait for your love)",
  "billie eilish|chihiro",
  "pawsa|dirty cash (money talks)",
  "blond:ish|never walk alone",
  "dj snake|paradise",
  "linkin park|up from the bottom",
  "olly alexander|desire",
  "grace potter|something that i want",
  "meghan trainor|to the moon",
  "beyoncé|ii most wanted",
  "ariana grande|hate that i made you love me",
  "rvssian|santa",
  "olivia rodrigo|drop dead",
  "indochine|le chant des cygnes",
  "sabrina carpenter|taste",
  "sombr|undressed",
  "ariana grande|yes, and?",
  "sza|saturn",
  "olivia rodrigo|obsessed",
  "nilo|fui mlk",
  "babymetal|ratatata",
  "linkin park|heavy is the crown",
  "deftones|my mind is a mountain",
  "james hype|seratonin",
  "galantis|lighter",
  "aya nakamura|baddies",
  "swedish house mafia|finally",
  "cyril|still into you",
  "fisher|waiting for tonight",
  "roya|cruise",
  "nosi|so good",
  "tobiahs|lifetime",
  "massh|all i got",
  "benson boone|mystical magical",
  "tems|what you need",
  "stromae|ma meilleure ennemie (from the series arcane league of legends)",
  "olivia rodrigo|stupid song",
  "stella lefty|boston",
  "kehlani|folded",
  "charli xcx|chains of love",
  "damiano david|next summer",
  "kabin crew|the spark",
  "fontaines d.c.|here's the thing",
  "kris kross amsterdam|queen of my castle",
  "lost frequencies|black friday (pretty like the sun)",
  "nimino|i only smoke when i drink",
  "kygo|chasing paradise",
  "tove lo|heat",
  "elderbrook|shallow water",
  "giveon|twenties",
  "summer walker|heart of a woman",
  "saja boys|soda pop",
  "ofenbach|miles away",
  "linkin park|the emptiness machine",
  "sam fender|rein me in",
  "benson boone|sorry i'm here for someone else",
  "ella henderson|filthy rich",
  "the black keys|beautiful people (stay high)",
  "kacey musgraves|the architect",
  "shaka ponk|i'm picky (unplugged)",
  "billie eilish|lunch",
  "bring me the horizon|kool-aid",
  "judas priest|the serpent and the king",
  "the strokes|falling out of love",
  "linkin park|two faced",
  "deep purple|portable door",
  "judas priest|crown of horns",
  "deftones|milk of the madonna",
  "halestorm|everest",
  "the lathums|no direction",
  "wet leg|cpr",
  "the story so far|letterman",
  "john maus|i hate antichrist",
  "ulysse marshall|> sans issue",
  "curtain|mother",
  "deus ex lumina|facade of the decay",
  "the sweet kill|blood red roses",
  "blind delon|étoile froide",
  "harsh symmetry|stained glass",
  "curtain|between us",
  "bleu grave|killjoy",
  "the cure|a fragile thing",
  "night in athens|words unspoken",
  "kim gordon|i'm a man",
  "she past away|i̇nziva",
  "cold cave|she reigns down",
  "nick cave & the bad seeds|wild god",
  "saiph|feel the night",
  "hugel|forever (feat. malou & yuna)",
  "oldilla|deixa o cavalo correr",
  "myles smith|nice to meet you (feat. lainey wilson)",
  "deejhay rb|longe de magnata",
  "huntr/x|golden (david guetta rem/x extended)",
  "maz|jolie fille (feat. layefa)",
  "charli xcx|guess featuring billie eilish",
  "harry styles|american girls",
  "billie eilish|wildflower",
  "dimitri vegas & like mike|thank you (not so bad) (extended)",
  "disney|zoo (from \"zootopia 2\")",
  "kendrick lamar|tv off",
  "kendrick lamar|peekaboo",
  "oldilla|cuida do pet",
  "blackpink|jump",
  "ofenbach|four to the floor",
  "playboi carti|good credit",
  "kendrick lamar|wacced out murals",
  "drake|circadian rhythm",
  "marten lou|your body",
  "taylor swift|i knew it, i knew you (from \"toy story 5\")",
  "sevdaliza|alibi (with pabllo vittar & yseult)",
  "dave|raindance",
  "electric callboy|we got the moves",
  "malcolm todd|earrings",
  "addison rae|diet pepsi",
  "meghan trainor|criminals",
  "tommygunnz|lose yourself",
  "kopy kat|till i collapse",
  "dillin hoox|lose my mind",
  "shadow|middle child",
  "playboi carti|evil j0rdan",
  "future|like that",
  "eminem|fuel",
  "kopy kat|big dawgs",
  "drake|gimme a hug",
  "shadow|no role modelz",
  "playboi carti|cocaine nose",
  "anup4m|the next episode",
  "mahaji|gaslight",
  "offset|swing my way",
  "choco lit papii|trending topic",
  "tyler, the creator|rah tah tah",
  "drama b|the voicemail",
  "future|teflon don",
  "mahaji|uhh freestyle",
  "dillin hoox|coming for the belt",
  "the bausa|magnetic",
  "&me|thandaza",
  "naarly|what i need",
  "lisa|new woman (feat. rosalía)",
  "zach bryan|28",
  "kygo|for life (feat. nile rodgers)",
  "tate mcrae|revolving door",
  "the kid laroi|baby i'm back",
  "thomas rhett|somethin' 'bout a woman",
  "pinkpantheress|stateside + zara larsson",
  "kurt darren|hop hop spinnekop",
  "olivia dean|a couple minutes",
  "lukão mec|passa o teu bigode 2",
  "coldplay|all my love",
  "fwd/slash|say it right",
  "lainey wilson|4x4xu",
  "scotty mccreery|bottle rockets (feat. hootie & the blowfish)",
  "luke combs|back in the saddle",
  "tyler braden|god & guns n’ roses",
  "cody johnson|the fall",
  "tucker wetmore|brunette",
  "josh ross|hate how you look",
  "bruno mars|risk it all",
  "twenty one pilots|drag path",
  "tate mcrae|just keep watching (from f1® the movie)",
  "coldplay|we pray (tini version)",
  "alex warren|bloodline",
  "gracie abrams|that’s so true",
  "raffa guido|famax",
  "jerry ropero|coraçao",
  "ed sheeran|azizam",
  "tayna|si ai",
  "antdot|corpo e canção",
  "future|type shit",
  "bleu soleil|soleil bleu",
  "morgan seatree|say my name",
  "chrystal|the days",
  "booker t. & the m.g.'s|green onions",
  "fleetwood mac|albatross",
  "van halen|eruption",
  "rush|2112: overture / the temples of syrinx / discovery / presentation / oracle / soliloquy / grand finale (medley)",
  "kelly key|sou a barbie girl",
  "michel teló|ai se eu te pego! (ao vivo)",
  "tchakabum|dança da mãozinha (ao vivo)",
].map((s) => s.toLowerCase()));

/** True if this song should never reach the deck. */
export function isExcluded(song) {
  if (EXCLUDED_ARTISTS.has(String(song.artist).toLowerCase())) return true;
  return EXCLUDED_SONGS.has(`${song.artist}|${song.title}`.toLowerCase());
}
